

clean:
	rm -rf content/*.aux
	rm -rf paper.aux
	rm -rf paper.bbl
	rm -rf paper.out
	rm -rf paper.blg
	rm -rf paper.dvi
	rm -rf paper.lof
	rm -rf paper.log
	rm -rf paper.lot
	rm -rf paper.pdf
	rm -rf paper.tcp
	rm -rf paper.synctex.gz
	rm -rf paper.toc
	rm -rf paper.tps
